version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/angular-ecom-main

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 500
      runas: root

  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 500
      runas: root
