version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Building the Angular application...
      - npm run build -- --configuration=production --output-path=dist/angular-ecom-main
      - echo Listing the contents of the dist directory...
      - ls -R dist

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/angular-ecom-main/ s3://ecom-app-artifacts/dist-angular-ecom-main/

artifacts:
  files:
    - '**/*'
  base-directory: dist/angular-ecom-main
