version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install dependencies
      echo Installing dependencies...
      npm install --legacy-peer-deps

  build:
    commands:
      # Build Angular application in production mode
      echo Building the Angular application...
      npm run build -- --configuration=production --output-path=dist/angular-ecom-main

  post_build:
    commands:
      # Upload the built files to the S3 bucket
      echo Deploying to S3...
      aws s3 sync dist/angular-ecom-main/ s3://your-s3-bucket-name --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist/angular-ecom-main


